"""Content & communication generation (SRD §29, §56).

Posts, cover letters, and job-application answers — all grounded in the persona
via retrieval, generated by the LLM, and checked by the claim validator. The
validator does not rewrite prose here (that would mangle it); instead it surfaces
any unsupported claims as warnings so the user can fix them before sending.
"""

from __future__ import annotations

from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.ai.llm import get_llm
from app.ai.llm.base import Message
from app.ai.rag.retrieval import build_context_block, retrieve
from app.ai.rag.validation import ClaimStatus, validate_text
from app.ai.writing_style import style_descriptor
from app.core.config import settings
from app.domain.career import analyze_jd, match_jd, summarize_gap
from app.models.persona import Persona, WritingStyle

CONTENT_TYPES = {
    "linkedin_post": "a LinkedIn post (concise, a few short paragraphs, 1-3 hashtags)",
    "x_post": "an X/Twitter post (under 280 characters, punchy)",
    "blog_post": "a blog post (clear structure with a short intro, body, and takeaway)",
    "project_announcement": "a project announcement (what it does, the stack, and why it matters)",
    "technical_article": "a technical article (explanatory, with concrete detail)",
}

TONES = {"professional", "casual", "enthusiastic", "concise", "technical"}


async def _generate(
    system: str,
    user: str,
    *,
    purpose: str,
    max_tokens: int = 1200,
) -> str:
    llm = get_llm()
    messages: list[Message] = [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]
    result = await llm.complete(
        messages, model=settings.llm_model_strong, max_tokens=max_tokens,
        temperature=0.6, purpose=purpose,
    )
    return result.text.strip()


async def _style_hint(session: AsyncSession, persona: Persona) -> str:
    row = (
        await session.execute(select(WritingStyle).where(WritingStyle.persona_id == persona.id))
    ).scalar_one_or_none()
    return style_descriptor(row.metrics) if row and row.metrics else ""


def _warnings(text: str, evidence: str) -> list[str]:
    """Unsupported specific claims, surfaced (not auto-removed)."""
    warnings: list[str] = []
    for v in validate_text(text, evidence):
        if v.status == ClaimStatus.reject:
            warnings.append(f"Unsupported: “{v.claim[:120]}” ({v.reason})")
        elif v.status == ClaimStatus.downgrade:
            warnings.append(f"Overclaim: “{v.claim[:120]}” — {v.reason}")
    return warnings[:8]


async def generate_content(
    session: AsyncSession,
    persona: Persona,
    *,
    content_type: str,
    topic: str,
    tone: str = "professional",
) -> dict[str, Any]:
    descriptor = CONTENT_TYPES.get(content_type, CONTENT_TYPES["linkedin_post"])
    tone = tone if tone in TONES else "professional"

    ctx = await retrieve(session, persona, topic or "my professional background")
    context_block = build_context_block(ctx)
    name = persona.full_name or "the author"
    style = await _style_hint(session, persona)

    system = (
        f"You are writing as {name}. Write {descriptor} in a {tone} tone.\n"
        "Ground everything in the background below — do NOT invent experience, "
        "metrics, employers, or projects that are not present. Write in first "
        f"person. {style} Return only the content, no preamble.\n\n"
        f"Background:\n{context_block}"
    )
    content = await _generate(
        system, f"Topic: {topic}", purpose="generate_content"
    )
    return {
        "content": content,
        "warnings": _warnings(content, context_block),
        "content_type": content_type,
        "tone": tone,
    }


async def generate_cover_letter(
    session: AsyncSession,
    persona: Persona,
    *,
    job_description: str,
    company: str | None = None,
    tone: str = "professional",
) -> dict[str, Any]:
    jd = await analyze_jd(job_description)
    matches = await match_jd(session, persona, jd)
    gap = summarize_gap(matches)
    supported = gap["strongly_supported"] + gap["partially_supported"]

    ctx = await retrieve(session, persona, " ".join(jd.required_skills + jd.technologies))
    context_block = build_context_block(ctx)
    name = persona.full_name or "the applicant"
    role = jd.title or "the role"
    company_txt = f" at {company}" if company else ""

    system = (
        f"You are writing a cover letter as {name} for {role}{company_txt}, in a "
        f"{tone} tone. Highlight the candidate's genuinely relevant strengths "
        f"(especially: {', '.join(supported[:8]) or 'their background'}). Ground "
        "every claim in the background below — never fabricate experience, "
        "numbers, or employers. Three to four short paragraphs. Return only the "
        f"letter.\n\nBackground:\n{context_block}"
    )
    content = await _generate(
        system, f"Job description:\n{job_description[:4000]}",
        purpose="cover_letter", max_tokens=1000,
    )
    return {
        "content": content,
        "warnings": _warnings(content, context_block),
        "matched": supported,
        "missing": gap["not_demonstrated"],
    }


async def generate_application_answer(
    session: AsyncSession,
    persona: Persona,
    *,
    question: str,
    job_description: str | None = None,
) -> dict[str, Any]:
    query = f"{question} {job_description or ''}"
    ctx = await retrieve(session, persona, query)
    context_block = build_context_block(ctx)
    name = persona.full_name or "the applicant"

    system = (
        f"You are answering a job-application question as {name}. Answer honestly "
        "and specifically, grounded ONLY in the background below. Do not invent "
        "experience or details. Be concise (one to two short paragraphs). Return "
        f"only the answer.\n\nBackground:\n{context_block}"
    )
    content = await _generate(
        system, f"Question: {question}", purpose="application_answer",
        max_tokens=700,
    )
    return {"content": content, "warnings": _warnings(content, context_block)}
