"""persona core

Revision ID: b2a9375ab477
Revises: 7f17c8c76b58
Create Date: 2026-10-02 12:07:47.323446
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b2a9375ab477'
down_revision: str | None = '7f17c8c76b58'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('headline', sa.String(length=300), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_user_id'), 'personas', ['user_id'], unique=False)
    op.create_table('achievements',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_awarded', sa.Date(), nullable=True),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', 'public', name='visibility', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.Enum('verified', 'inferred', 'user_confirmed', 'unknown', name='evidencestate', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_persona_id'), 'achievements', ['persona_id'], unique=False)
    op.create_table('certifications',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', 'public', name='visibility', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.Enum('verified', 'inferred', 'user_confirmed', 'unknown', name='evidencestate', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_persona_id'), 'certifications', ['persona_id'], unique=False)
    op.create_table('education',
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=True),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', 'public', name='visibility', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.Enum('verified', 'inferred', 'user_confirmed', 'unknown', name='evidencestate', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_persona_id'), 'education', ['persona_id'], unique=False)
    op.create_table('evidence',
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('persona', 'skill', 'experience', 'project', 'education', 'achievement', 'publication', 'certification', 'knowledge_area', 'preference', name='entitytype', native_enum=False, length=32), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Enum('verified', 'inferred', 'user_confirmed', 'unknown', name='evidencestate', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_entity_id'), 'evidence', ['entity_id'], unique=False)
    op.create_index(op.f('ix_evidence_persona_id'), 'evidence', ['persona_id'], unique=False)
    op.create_table('experiences',
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('employment_type', sa.Enum('job', 'internship', 'freelance', 'open_source', 'volunteer', 'leadership', name='employmenttype', native_enum=False, length=32), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', 'public', name='visibility', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.Enum('verified', 'inferred', 'user_confirmed', 'unknown', name='evidencestate', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiences_persona_id'), 'experiences', ['persona_id'], unique=False)
    op.create_table('knowledge_areas',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', 'public', name='visibility', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.Enum('verified', 'inferred', 'user_confirmed', 'unknown', name='evidencestate', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_areas_persona_id'), 'knowledge_areas', ['persona_id'], unique=False)
    op.create_table('persona_versions',
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_versions_persona_id'), 'persona_versions', ['persona_id'], unique=False)
    op.create_table('preferences',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('explicit', 'inferred_pending', 'confirmed', name='preferencesource', native_enum=False, length=32), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', 'public', name='visibility', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.Enum('verified', 'inferred', 'user_confirmed', 'unknown', name='evidencestate', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferences_persona_id'), 'preferences', ['persona_id'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', 'public', name='visibility', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.Enum('verified', 'inferred', 'user_confirmed', 'unknown', name='evidencestate', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_persona_id'), 'projects', ['persona_id'], unique=False)
    op.create_table('publications',
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('venue', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', 'public', name='visibility', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.Enum('verified', 'inferred', 'user_confirmed', 'unknown', name='evidencestate', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_persona_id'), 'publications', ['persona_id'], unique=False)
    op.create_table('skills',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('canonical_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', 'public', name='visibility', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.Enum('verified', 'inferred', 'user_confirmed', 'unknown', name='evidencestate', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_canonical_name'), 'skills', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_skills_persona_id'), 'skills', ['persona_id'], unique=False)
    op.create_table('writing_styles',
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_styles_persona_id'), 'writing_styles', ['persona_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_writing_styles_persona_id'), table_name='writing_styles')
    op.drop_table('writing_styles')
    op.drop_index(op.f('ix_skills_persona_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_canonical_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_publications_persona_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_projects_persona_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_preferences_persona_id'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_persona_versions_persona_id'), table_name='persona_versions')
    op.drop_table('persona_versions')
    op.drop_index(op.f('ix_knowledge_areas_persona_id'), table_name='knowledge_areas')
    op.drop_table('knowledge_areas')
    op.drop_index(op.f('ix_experiences_persona_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_evidence_persona_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_entity_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_education_persona_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_certifications_persona_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_achievements_persona_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_personas_user_id'), table_name='personas')
    op.drop_table('personas')
    # ### end Alembic commands ###
